#include"../Object/Node/ObjectBase.h"
#include"../Object/Node/Square.h"
#include"../Object/Node/Triangle.h"
#include"../Object/Node/Sprite.h"
#include"../Object/Node/Cube.h"
#include"../Object/Node/MaterialDecorator.h"
#include"../Object/Node/TextureDecorator.h"